export const ROUTES = {
  home: "/",
  designSystem: "/design-system",
  auth: {
    splash: "/splash",
    onboarding: "/onboarding",
    login: "/login",
    forgotPassword: "/forgot-password",
    roleSelection: "/role-selection",
    register: "/register",
    registerDonor: "/register?role=donor",
    registerNgo: "/register?role=ngo",
    registerVolunteer: "/register?role=volunteer",
  },
  preview: {
    donor: "/preview/donor",
    ngo: "/preview/ngo",
  },
  donor: {
    dashboard: "/donor/dashboard",
    donations: "/donor/donations",
    newDonation: "/donor/donations/new",
    ngos: "/donor/ngos",
    notifications: "/donor/notifications",
    profile: "/donor/profile",
    editProfile: "/donor/profile/edit",
    addresses: "/donor/addresses",
    settings: "/donor/settings",
    support: "/donor/support",
    donation: (donationId: string) => `/donor/donations/${donationId}`,
    donationTracking: (donationId: string) => `/donor/donations/${donationId}/tracking`,
    ngoProfile: (ngoId: string) => `/donor/ngos/${ngoId}`,
  },
  ngo: {
    dashboard: "/ngo/dashboard",
    discover: "/ngo/discover",
    discoverMap: "/ngo/discover/map",
    claims: "/ngo/claims",
    requests: "/ngo/requests",
    newRequest: "/ngo/requests/new",
    requestSubmitted: "/ngo/requests/submitted",
    impact: "/ngo/impact",
    notifications: "/ngo/notifications",
    profile: "/ngo/profile",
    editProfile: "/ngo/profile/edit",
    team: "/ngo/team",
    verification: "/ngo/verification",
    settings: "/ngo/settings",
    support: "/ngo/support",
    donation: (donationId: string) => `/ngo/donations/${donationId}`,
    claim: (claimId: string) => `/ngo/claims/${claimId}`,
    confirmDelivery: (claimId: string) => `/ngo/claims/${claimId}/confirm-delivery`,
    distribution: (claimId: string) => `/ngo/claims/${claimId}/distribution`,
    reportIssue: (claimId: string) => `/ngo/claims/${claimId}/report-issue`,
    request: (requestId: string) => `/ngo/requests/${requestId}`,
  },
} as const;

export const AUTH_NAVIGATION = [
  { label: "Welcome", href: ROUTES.auth.splash },
  { label: "Get started", href: ROUTES.auth.onboarding },
  { label: "Log in", href: ROUTES.auth.login },
  { label: "Choose role", href: ROUTES.auth.roleSelection },
] as const;
