"use client";
import { useEffect, useState, type FormEvent } from "react";
import { Mail, UserPlus, UsersRound } from "lucide-react";
import { PortalShell } from "@/components/layout/portal-shell"; import { Alert } from "@/components/ui/alert"; import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent, CardHeader } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Select } from "@/components/ui/select";
import { NGO_ACCOUNT_PROFILE_ID, NGO_ACCOUNT_VIEWER } from "@/features/ngo-account/shared"; import { ROUTES } from "@/lib/routes"; import { ngoAccountService, toServiceError } from "@/services"; import type { NGOTeamMember, NGOTeamRole } from "@/types/domain";
const ROLE_LABELS: Record<NGOTeamRole, string> = { OWNER: "Owner", COORDINATOR: "Coordinator", FIELD_STAFF: "Field staff", VIEWER: "Viewer" };
export function NGOTeam() { const [members, setMembers] = useState<NGOTeamMember[]>([]); const [form, setForm] = useState({ name: "", email: "", role: "VIEWER" as NGOTeamRole }); const [message, setMessage] = useState<string>(); const [error, setError] = useState<string>();
  useEffect(() => { ngoAccountService.listTeam(NGO_ACCOUNT_PROFILE_ID, NGO_ACCOUNT_VIEWER).then(setMembers).catch((caught) => setError(toServiceError(caught).message)); }, []);
  async function invite(event: FormEvent) { event.preventDefault(); setError(undefined); try { const member = await ngoAccountService.inviteMember(NGO_ACCOUNT_PROFILE_ID, form, NGO_ACCOUNT_VIEWER); setMembers((current) => [...current, member]); setForm({ name: "", email: "", role: "VIEWER" }); setMessage("Mock invitation recorded. No email was sent."); } catch (caught) { setError(toServiceError(caught).message); } }
  return <PortalShell role="ngo" activeHref={ROUTES.ngo.profile} title="Team & permissions" description="Manage mock organization access without sending real invitations." profileName="Hope Foundation" profileDescription="Verified NGO" avatarInitials="HF" notificationHref={ROUTES.ngo.notifications}><div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><Card><CardHeader title="Organization members" description={`${members.filter((item) => item.status === "ACTIVE").length} active members`} action={<UsersRound className="size-5 text-brand-700" />} /><CardContent className="grid gap-3">{members.map((member) => <div key={member.id} className="flex flex-wrap items-center gap-3 rounded-card border border-line p-4"><span className="grid size-10 place-items-center rounded-full bg-brand-100 font-bold text-brand-800">{member.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><div className="min-w-0 flex-1"><p className="font-semibold text-ink-900">{member.name}</p><p className="text-xs text-muted-600">{member.email}</p></div><Badge tone={member.status === "ACTIVE" ? "success" : "warning"}>{member.status.toLowerCase()}</Badge><Badge tone="neutral">{ROLE_LABELS[member.role]}</Badge></div>)}</CardContent></Card><form onSubmit={invite}><Card><CardHeader title="Invite member" description="Frontend-only invitation UI." /><CardContent className="grid gap-4"><Input label="Full name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input label="Email" type="email" leftIcon={<Mail className="size-4" />} value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><Select label="Role" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as NGOTeamRole })}>{Object.entries(ROLE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select>{error && <Alert tone="danger" title="Invite not recorded" description={error} />}{message && <Alert tone="success" title="Invitation ready" description={message} />}<Button type="submit" fullWidth leftIcon={<UserPlus className="size-4" />}>Invite member</Button></CardContent></Card></form></div></PortalShell>; }
