"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Save } from "lucide-react";
import { PortalShell } from "@/components/layout/portal-shell";
import { Alert } from "@/components/ui/alert";
import { Button, ButtonLink } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { NGO_ACCOUNT_USER_ID, NGO_ACCOUNT_VIEWER } from "@/features/ngo-account/shared";
import { ROUTES } from "@/lib/routes";
import { profileService, toServiceError } from "@/services";

export function NGOProfileEditor() {
  const [form, setForm] = useState({ organizationName: "", summary: "", mission: "", vision: "", serviceAreas: "", beneficiaryTypes: "", capacityMealsPerDay: "", publicEmail: "", publicPhone: "" });
  const [ready, setReady] = useState(false); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [errors, setErrors] = useState<Record<string, string>>({});
  useEffect(() => { const controller = new AbortController(); profileService.getOwnProfile(NGO_ACCOUNT_USER_ID, NGO_ACCOUNT_VIEWER, { signal: controller.signal }).then(({ ngoProfile }) => { if (!ngoProfile) return; setForm({ organizationName: ngoProfile.organizationName, summary: ngoProfile.summary, mission: ngoProfile.mission, vision: ngoProfile.vision, serviceAreas: ngoProfile.serviceAreas.join(", "), beneficiaryTypes: ngoProfile.beneficiaryTypes.join(", "), capacityMealsPerDay: String(ngoProfile.capacityMealsPerDay), publicEmail: ngoProfile.publicEmail, publicPhone: ngoProfile.publicPhone }); setReady(true); }); return () => controller.abort(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setSaved(false); setErrors({}); try { await profileService.updateNGOProfile(NGO_ACCOUNT_USER_ID, { ...form, capacityMealsPerDay: Number(form.capacityMealsPerDay), serviceAreas: form.serviceAreas.split(","), beneficiaryTypes: form.beneficiaryTypes.split(",") }, NGO_ACCOUNT_VIEWER); setSaved(true); } catch (caught) { const issue = toServiceError(caught); setErrors(issue.fieldErrors ?? { form: issue.message }); } finally { setSaving(false); } }
  return <PortalShell role="ngo" activeHref={ROUTES.ngo.profile} title="Edit organization" description="Keep public information and operational capacity accurate." profileName={form.organizationName || "Hope Foundation"} profileDescription="Verified NGO" avatarInitials="HF" notificationHref={ROUTES.ngo.notifications} actions={<ButtonLink href={ROUTES.ngo.profile} variant="ghost" size="sm">Cancel</ButtonLink>}>{ready && <form onSubmit={submit} className="grid gap-5"><Card><CardHeader title="Public organization details" description="These fields may appear in the verified donor directory." /><CardContent className="grid gap-5 sm:grid-cols-2"><Input label="Organization name" value={form.organizationName} error={errors.organizationName} onChange={(e) => setForm({ ...form, organizationName: e.target.value })} /><Input label="Daily meal capacity" type="number" min="1" value={form.capacityMealsPerDay} error={errors.capacityMealsPerDay} onChange={(e) => setForm({ ...form, capacityMealsPerDay: e.target.value })} /><Textarea label="Summary" value={form.summary} error={errors.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} containerClassName="sm:col-span-2" /><Textarea label="Mission" value={form.mission} onChange={(e) => setForm({ ...form, mission: e.target.value })} /><Textarea label="Vision" value={form.vision} onChange={(e) => setForm({ ...form, vision: e.target.value })} /><Input label="Service areas" value={form.serviceAreas} error={errors.serviceAreas} hint="Comma-separated areas" onChange={(e) => setForm({ ...form, serviceAreas: e.target.value })} /><Input label="Beneficiary groups" value={form.beneficiaryTypes} hint="Comma-separated groups" onChange={(e) => setForm({ ...form, beneficiaryTypes: e.target.value })} /><Input label="Public email" type="email" value={form.publicEmail} error={errors.publicEmail} onChange={(e) => setForm({ ...form, publicEmail: e.target.value })} /><Input label="Public phone" value={form.publicPhone} error={errors.publicPhone} onChange={(e) => setForm({ ...form, publicPhone: e.target.value })} /></CardContent></Card>{errors.form && <Alert tone="danger" title="Profile could not be saved" description={errors.form} />}{saved && <Alert tone="success" title="Profile updated" description="Changes are reflected in the frontend mock state." />}<div className="flex justify-end"><Button type="submit" disabled={saving} leftIcon={<Save className="size-4" />}>{saving ? "Saving…" : "Save changes"}</Button></div></form>}</PortalShell>;
}
